//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOMBPKB
    {
        #region Primitive Properties
    
        public virtual string PONUMBER
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDBPKBDICAB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDBPKBDIHO
        {
            get;
            set;
        }
    
        public virtual string DETAILPROBLEM
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DELIVERYDATEBPKB
        {
            get;
            set;
        }
    
        public virtual string KETSURATUBAHBENTUK
        {
            get;
            set;
        }
    
        public virtual string KETBPKB
        {
            get;
            set;
        }
    
        public virtual string KETKAROSERI
        {
            get;
            set;
        }
    
        public virtual string LOKASIBPKB
        {
            get;
            set;
        }
    
        public virtual string NOFAKTUR
        {
            get;
            set;
        }
    
        public virtual string NOFORMULIRA
        {
            get;
            set;
        }
    
        public virtual string NOSERTIFIKAT
        {
            get;
            set;
        }
    
        public virtual string NOSURATUBAHBENTUK
        {
            get;
            set;
        }
    
        public virtual string NOSERTIFIKATREGUJITIPE
        {
            get;
            set;
        }
    
        public virtual string NOBPKB
        {
            get;
            set;
        }
    
        public virtual string NOPOLISI
        {
            get;
            set;
        }
    
        public virtual string POSISIBPKB
        {
            get;
            set;
        }
    
        public virtual string PROGRESBPKB
        {
            get;
            set;
        }
    
        public virtual string STATUSBPKB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLFAKTUR
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLFORMULIRA
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSERAHBPKB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSERTIFIKAT
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSURATUBAHBENTUK
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLGRBPKB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSTNK
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLBPKBDIKIRIMKEMBALI
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALDELIVERYBPKBTOFINANCE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DATEDELIVERYTOBRANCHORVENDOR
        {
            get;
            set;
        }
    
        public virtual string REMARKSDETAILPROBLEM
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ACTUALRECEIVEDBPKBHOBACK
        {
            get;
            set;
        }
    
        public virtual string MODIFIED_BY
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MODIFIED_DATE
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> STCKDATE
        {
            get;
            set;
        }
    
        public virtual string NOPOLISI_INPUT
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLSTNK_INPUT
        {
            get;
            set;
        }
    
        public virtual string REASONREVISEBPKB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> REVISEDATE
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> isRevised
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TGLPROMISEDELIVERYBPKB
        {
            get;
            set;
        }
    
        public virtual string NOSURATRUBAHWARNA
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TANGGALSURATRUBAHWARNA
        {
            get;
            set;
        }
    
        public virtual string KETERANGANSURATRUBAHWARNA
        {
            get;
            set;
        }

        #endregion

    }
}
