//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_S02007
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TransactionDataID
        {
            get;
            set;
        }
    
        public virtual string PONUMBER
        {
            get;
            set;
        }
    
        public virtual Nullable<int> VERSIONPOSERA
        {
            get;
            set;
        }
    
        public virtual string BILLINGNO
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> INVOICERECEIPTDATE
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DATAVERSION
        {
            get;
            set;
        }
    
        public virtual string dibuatOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dibuatTanggal
        {
            get;
            set;
        }
    
        public virtual string diubahOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> diubahTanggal
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> payPlan
        {
            get;
            set;
        }

        #endregion

    }
}
