//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_S02002
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TransactionDataID
        {
            get { return _transactionDataID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_transactionDataID != value)
                    {
                        if (CUSTOM_DOWNLOAD_TRANSACTIONDATA != null && CUSTOM_DOWNLOAD_TRANSACTIONDATA.ID != value)
                        {
                            CUSTOM_DOWNLOAD_TRANSACTIONDATA = null;
                        }
                        _transactionDataID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _transactionDataID;
    
        public virtual string PONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> VersionPOSERA
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> DataVersion
        {
            get;
            set;
        }
    
        public virtual string StatusPOSERA
        {
            get;
            set;
        }
    
        public virtual string RejectRevisedPOSERA
        {
            get;
            set;
        }
    
        public virtual string DocumentNo
        {
            get;
            set;
        }
    
        public virtual string AIMaterialNumber
        {
            get;
            set;
        }
    
        public virtual string SERAMaterialNumber
        {
            get;
            set;
        }
    
        public virtual string SERAMaterialDescription
        {
            get;
            set;
        }
    
        public virtual string AIColor
        {
            get;
            set;
        }
    
        public virtual string SERAColor
        {
            get;
            set;
        }
    
        public virtual string QuotationNo
        {
            get;
            set;
        }
    
        public virtual string SalesOrderNo
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SalesOrderStatus
        {
            get;
            set;
        }
    
        public virtual Nullable<double> DPPByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<double> PPNByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<double> BBNPriceByVendor
        {
            get;
            set;
        }
    
        public virtual string Currency
        {
            get;
            set;
        }
    
        public virtual string ChassisNumberByVendor
        {
            get;
            set;
        }
    
        public virtual string MachineNumberByVendor
        {
            get;
            set;
        }
    
        public virtual string CBUCKD
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Year
        {
            get;
            set;
        }
    
        public virtual string FactureDONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> BillingStatus
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FactureDODate
        {
            get;
            set;
        }
    
        public virtual string NoFakturKendaraan
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TanggalFakturKendaraan
        {
            get;
            set;
        }
    
        public virtual string CancellationReason
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ActualDateDeliveryUnit
        {
            get;
            set;
        }
    
        public virtual string BSTKBNo
        {
            get;
            set;
        }
    
        public virtual string LicensePlateByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> STNKDateByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RevisiSTNK
        {
            get;
            set;
        }
    
        public virtual string NoSertifikat
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TglSertifikat
        {
            get;
            set;
        }
    
        public virtual string NoFormulirA
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TglFormulirA
        {
            get;
            set;
        }
    
        public virtual string NoSertifikatRegUjiTipe
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ActualDeliveryBPKBDate
        {
            get;
            set;
        }
    
        public virtual string NamaPenerima
        {
            get;
            set;
        }
    
        public virtual string AlamatPenerima
        {
            get;
            set;
        }
    
        public virtual string BPKBNumber
        {
            get;
            set;
        }
    
        public virtual string RemarksBPKB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RevisiBPKB
        {
            get;
            set;
        }
    
        public virtual string dibuatOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dibuatTanggal
        {
            get;
            set;
        }
    
        public virtual string diubahOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> diubahTanggal
        {
            get;
            set;
        }
    
        public virtual string xmlStatus
        {
            get;
            set;
        }
    
        public virtual string xmlCreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlCreatedDate
        {
            get;
            set;
        }
    
        public virtual string xmlModifiedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> xmlModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual CUSTOM_DOWNLOAD_TRANSACTIONDATA CUSTOM_DOWNLOAD_TRANSACTIONDATA
        {
            get { return _cUSTOM_DOWNLOAD_TRANSACTIONDATA; }
            set
            {
                if (!ReferenceEquals(_cUSTOM_DOWNLOAD_TRANSACTIONDATA, value))
                {
                    var previousValue = _cUSTOM_DOWNLOAD_TRANSACTIONDATA;
                    _cUSTOM_DOWNLOAD_TRANSACTIONDATA = value;
                    FixupCUSTOM_DOWNLOAD_TRANSACTIONDATA(previousValue);
                }
            }
        }
        private CUSTOM_DOWNLOAD_TRANSACTIONDATA _cUSTOM_DOWNLOAD_TRANSACTIONDATA;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCUSTOM_DOWNLOAD_TRANSACTIONDATA(CUSTOM_DOWNLOAD_TRANSACTIONDATA previousValue)
        {
            if (previousValue != null && previousValue.CUSTOM_S02002.Contains(this))
            {
                previousValue.CUSTOM_S02002.Remove(this);
            }
    
            if (CUSTOM_DOWNLOAD_TRANSACTIONDATA != null)
            {
                if (!CUSTOM_DOWNLOAD_TRANSACTIONDATA.CUSTOM_S02002.Contains(this))
                {
                    CUSTOM_DOWNLOAD_TRANSACTIONDATA.CUSTOM_S02002.Add(this);
                }
                if (TransactionDataID != CUSTOM_DOWNLOAD_TRANSACTIONDATA.ID)
                {
                    TransactionDataID = CUSTOM_DOWNLOAD_TRANSACTIONDATA.ID;
                }
            }
            else if (!_settingFK)
            {
                TransactionDataID = null;
            }
        }

        #endregion

    }
}
